############################################ DEFAULT
# 모든 프로파일에 공통으로 적용할 사항은 여기에 기입한다.
spring:
  profiles:
    active: local # default profile을 지정한다.
    group:
      local:
        - secret # local 구동 시 secret 프로파일도 구동, secret에 비밀키를 등록한다.

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: [클라이언트_ID값]
            client-secret: [클라이언트_시크릿값]
            client-authentication-method: client_secret_post
            redirect-uri: [redirect_url]
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - account_email
---
############################################ LOCAL

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor},classpath:db/seed/local # when you want to give test seed, add location test seed too

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

jwt:
  header: Authorization
  secret: aGVsbG8gd29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2EK # fill in base64 [command: echo {plain_text} | base64]
  refresh-token-secret: d29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2FkCg== # it must be different from the access key secret
  access-token-validity-in-seconds: 600 # 10 min
  refresh-token-validity-in-seconds: 86400 # 24 hour # ??? ?? ?? ? 1?

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/index.html

cloud:
  aws:
    credentials:
      accessKey: accessKey
      secretKey: secretKey
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: test
